apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ecom
  annotations:
    nginx.ingress.kubernetes.io/proxy-buffering: "off"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "300"
spec:
  rules:
    - http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service: { name: backend,  port: { number: 8080 } }
          - path: /chat
            pathType: Prefix
            backend:
              service: { name: chatbot,  port: { number: 8000 } }
          - path: /
            pathType: Prefix
            backend:
              service: { name: frontend, port: { number: 80 } }
